version: 2
jobs:
  test-arm:
    machine:
      image: default
    resource_class: arm.medium
    environment:
    - RUST_STABLE: stable
    steps:
    - checkout
    - run:
        name: Install Rust
        command: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
          chmod +x rustup.sh
          ./rustup.sh -y --default-toolchain $RUST_STABLE
          source "$HOME"/.cargo/env
    - run:
        command: cargo test --all-features -p tokio
workflows:
  ci:
    jobs:
    - test-arm
  version: 2
